version: '3.1'
services:
    db:
        image: postgres:14.1
        environment:
            - POSTGRES_DB=hyper
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
        volumes: 
            - ./db:/var/lib/postgresql/data
        network_mode: host

    peer_0:
        image: application_backend
        volumes:
            - ./backend:/root/workspace
        command: air
        working_dir: /root/workspace
        environment:
            - CONFIG_FILE=config.yaml
        network_mode: host

    migrations:
        image: node:17-buster-slim
        volumes:
            - ./migration:/opt/app/workspace
        command: sleep infinity
        environment:
            - PGHOST=localhost
            - PGUSER=admin
            - PGDATABASE=hyper
            - PGPASSWORD=admin
            - PGPORT=5432
            - CONFIG_FILE=./initial_data/config.yaml
        working_dir: /opt/app/workspace
        network_mode: host
        